// autogenerated by typings-for-css-modules-loader.
declare namespace ButtonScssNamespace {
  export interface IButtonScss {
    Button: string;
    "Button--blue": string;
    "Button--disabled": string;
    "Button--grey": string;
    "Button--inactive": string;
    "Button--large": string;
    "Button--loading": string;
    "Button--outline": string;
    "Button--red": string;
    "Button--small": string;
    "Button--subtle": string;
    "Button--xsmall": string;
    Button__content: string;
    button: string;
    buttonBlue: string;
    buttonContent: string;
    buttonDisabled: string;
    buttonGrey: string;
    buttonInactive: string;
    buttonLarge: string;
    buttonLoading: string;
    buttonOutline: string;
    buttonRed: string;
    buttonSmall: string;
    buttonSubtle: string;
    buttonXsmall: string;
    spin: string;
  }
}

declare const ButtonScssModule: ButtonScssNamespace.IButtonScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ButtonScssNamespace.IButtonScss;
};

export = ButtonScssModule;
